spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbit
